version: '3'
services:
  frontend:
    build: ./frontend/
    tty: true
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend/
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    depends_on:
      - postgres
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

